services:
  db:
    image: postgres:13
    container_name: pizzaria_db
    environment:
      - POSTGRES_USER=pizzariauser
      - POSTGRES_PASSWORD=pizzariapassword
      - POSTGRES_DB=pizzariadb
      - TZ=America/Manaus
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  api:
    build: ./api
    container_name: pizzaria_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    working_dir: /app/
    ports:
      - "8123:8000"
    volumes:
      - ./api:/app
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    container_name: pizzaria_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: always

  certbot:
    image: certbot/certbot
    container_name: pizzaria_certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data: