version: '3.8'

services:
  db:
    image: postgres:13
    container_name: pizzaria_db
    environment:
      POSTGRES_USER: pizzariauser
      POSTGRES_PASSWORD: pizzariapassword
      POSTGRES_DB: pizzariadb
      TZ: America/Manaus # Define o fuso hor√°rio para Manaus (GMT-4)
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: