version: '3.8'

services:
  db:
    image: postgres:13
    container_name: pizzaria_db
    environment:
      POSTGRES_USER: pizzariauser
      POSTGRES_PASSWORD: pizzariapassword
      POSTGRES_DB: pizzariadb
      TZ: America/Manaus
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  api:
    build: ./api
    container_name: pizzaria_api
    ports:
      - "8123:8000"
    volumes:
      - ./api:/app
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: